export { formatPriceXAF, handleOrderWhatsApp } from "./shared/utils";
export { BoutiqueTemplate } from "./fashion";
export { RestaurantTemplate } from "./restaurant";
export { CosmeticsTemplate } from "./cosmetics";
export { PharmacyTemplate } from "./pharmacy";
export { ElectronicsTemplate } from "./electronics";
export { RealEstateTemplate } from "./realestate";
export { ArtisanTemplate } from "./artisan";
export { TrainerTemplate } from "./trainer";
export { BookstoreTemplate } from "./bookstore";
export { SupermarketTemplate } from "./supermarket";
